micronaut:
  application:
    name: openapi-groups
  openapi:
    groups:
      visible:
        common-exclude: true
        packages: com.example.visible.*
        packages-exclude: com.example
#        primary: true
        # Seems overridden by the annotation title/version
#        filename: visiblegroup
